# Use Nginx image as the base image
FROM nginx:alpine

# Copy the Nginx configuration file from the host
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
